# 1. Input: 어디서 로그를 받을 것인가?
input {
    #################################3
    # Spring Boot에서 LogstashTcpSocketAppender를 사용하여 5000번 포트 주는 JSON 로그을 받을 경우 
    #   tcp {
    #     port => 5000
    #     codec => json_lines
    #   }
    #################################3

    # File을 직접 읽어서 진행할 경우
    file {
        # 컨테이너 내ㄴ부에서 로그 파일이 위치할 경로 (아래 docker-compose에서 마운트 해줄 예정)
        path => "/usr/share/logstash/spring-logs/*.log"
        
        # 처음 실행될 때 파일의 처음부터 읽을지(beginning), 끝부터 읽을지(end) 결정
        start_position => "beginning"
        
        # (선택) JSON 형태로 저장된 로그라면 자동으로 파싱하도록 설정
        codec => "json" 
    }
}

# 2. Filter: 데이터를 어떻게 가공할 것인가? (이번엔 원본 그대로 패스)
filter {
  # 필요하다면 여기서 특정 문자열을 자르거나 IP를 위치로 변환하는 작업을 합니다.
}

# 3. Output: 어디로 로그를 보낼 것인가?
output {
  # Elasticsearch로 전송
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-boot-logs-%{+YYYY.MM.dd}" # 매일매일 새로운 인덱스(테이블) 생성
  }
  
  # 데이터가 잘 들어오는지 Logstash 컨테이너 로그(화면)에서도 확인하기 위함
  stdout {
    codec => rubydebug
  }
}